# E-Commerce Marketplace Customer Analytics

## Data Cleaning

This notebook focuses on cleaning and preparing the raw dataset for SQL analysis, Power BI visualization, and machine learning.

### Objectives
- Correct data types
- Handle missing values
- Validate data consistency
- Prepare a clean dataset

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

## 2. Load Raw Dataset

In [2]:
dataset_path = "../Dataset/Raw/Sales.csv"

df = pd.read_csv(dataset_path, encoding="latin1")

print("Dataset loaded successfully.")

Dataset loaded successfully.

## 3. Convert Data Types

In [3]:
df.dtypes

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Country/Region     object
City               object
State              object
Postal Code       float64
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [ ]:
df["Order Date"] = pd.to_datetime(df["Order Date"],dayfirst=True)

df["Ship Date"] = pd.to_datetime(df["Ship Date"],dayfirst=True)

In [5]:
df[["Order Date", "Ship Date"]].dtypes

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

## 4. Handle Missing Values

In [6]:
df.isnull().sum()

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country/Region     0
City               0
State              0
Postal Code       11
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
dtype: int64

In [7]:
df["Postal Code"] = (df["Postal Code"].fillna("Unknown").astype(str))

In [8]:
df["Postal Code"].isnull().sum()

np.int64(0)

In [9]:
df["Postal Code"].dtype

dtype('O')

## 5. Data Validation

In [10]:
df[["Sales", "Quantity", "Discount", "Profit"]].describe().T

,count,mean,std,min,25%,50%,75%,max
Sales,9994.0,229.858001,623.245101,0.444,17.28000,54.4900,209.940,22638.480
Quantity,9994.0,3.789574,2.225110,1.000,2.00000,3.0000,5.000,14.000
Discount,9994.0,0.156203,0.206452,0.000,0.00000,0.2000,0.200,0.800
Profit,9994.0,28.656896,234.260108,-6599.978,1.72875,8.6665,29.364,8399.976

In [11]:
negative_sales = df[df["Sales"] < 0]

print(f"Negative Sales Records: {len(negative_sales)}")
negative_sales.head()

Negative Sales Records: 0

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country/Region, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

In [12]:
zero_sales = df[df["Sales"] == 0]

print(f"Zero Sales Records: {len(zero_sales)}")
zero_sales.head()

Zero Sales Records: 0

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country/Region, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

In [13]:
invalid_discount = df[
    (df["Discount"] < 0) |
    (df["Discount"] > 1)
]

print(f"Invalid Discount Records: {len(invalid_discount)}")

Invalid Discount Records: 0

In [14]:
invalid_quantity = df[df["Quantity"] <= 0]

print(f"Invalid Quantity Records: {len(invalid_quantity)}")

Invalid Quantity Records: 0

### Validate Date Columns

In [15]:
invalid_dates = df[df["Ship Date"] < df["Order Date"]]

print(f"Invalid Date Records: {len(invalid_dates)}")
invalid_dates.head()

Invalid Date Records: 0

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country/Region, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

In [16]:
df["Order ID"].duplicated().sum()

np.int64(4984)

In [17]:
df[df["Order ID"] == df["Order ID"].iloc[0]]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,INDMKB,2020-11-08,2020-11-11,sas,as,asa,asa,asas,asas,asas,42420.0,INDMKB,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136

In [18]:
df["Customer ID"].isnull().sum()

np.int64(0)

In [19]:
df["Product ID"].isnull().sum()

np.int64(0)

## Validation Findings

### Validation Summary

- Date columns were successfully converted to datetime format.
- Postal Code was converted to string and missing values were replaced with "Unknown".
- No duplicate transaction records were found.
- No negative sales values were detected.
- Discount values fall within the expected range (0–1).
- Quantity values are valid.
- Shipping dates occur after or on the corresponding order dates.
- Customer IDs and Product IDs contain no missing values.

The dataset passed all validation checks and is ready for feature engineering and SQL analysis.

## 6. Save Clean Dataset

In [20]:
output_path = "../Dataset/Processed/cleaned_sales.csv"

df.to_csv(output_path, index=False)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!